name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.2 [CE|EE|ECE 2.4.0-2.4.7] 03 Jul 2024
          tag_name: 1.5.2
          body: "### softcommerce/module-core [1.5.2]
            - **Fix**: Applied a fix to \SoftCommerce\Core\Model\Store\WebsiteStorage::getStoreIdToWebsiteId method where argument data type for $storeId was changed from string to an integer [#10]. "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
