name: Automated Release
on:
  push:
    branches:
      - "master"
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.6.1 [CE|EE|ECE 2.4.0-2.4.7] 28 May 2025
          tag_name: 1.6.1
          body: |-
            ### softcommerce/module-core [1.6.1]
            - **Enhancement**: Enhanced Configurable-Product Detection in Export/Import Interface [#64]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
