name: Automated Release
on:
  push:
    branches:
      - "master"
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.8 [CE|EE|ECE 2.4.0-2.4.7] 13 Jan 2025
          tag_name: 1.5.8
          body: |-
            ### softcommerce/module-core [1.5.8]
            - **Compatibility**: Added compatibility for PHP 8.4 and Magento 2.4.8-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
