name: Automated Release
on:
  push:
    branches:
      - "master"
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.6 [CE|EE|ECE 2.4.0-2.4.7] 27 Sep 2024
          tag_name: 1.5.6
          body: |-
            ### softcommerce/module-core [1.5.6]
            - **Enhancement**: Added an option to display installed metapackages for the bundled modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
