name: Automated Release
on:
  push:
    branches:
      - "master"
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.5.5 [CE|EE|ECE 2.4.0-2.4.7] 24 Sep 2024
          tag_name: 1.5.5
          body: |-
            ### softcommerce/module-core [1.5.5]
            - **Compatibility**: Add compatibility for Magento 2.4.7-p2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
